name: Test

on:
  push:
    branches-ignore:
      - gh-readonly-queue/**
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macOS-latest, windows-latest, ubuntu-20.04]
        # os: [ubuntu-latest, ubuntu-20.04]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install pkg-config cmake clang build-essential luarocks -y

    - name: Run tests
      run: |
        luarocks make --local
        lua ./spec/*.lua

    # this depends on the tag being pushed to github
    # so this would always fail before a release
    # thats annoying so lets not test it for now
    # - name: Test install
    #   run: |
    #     luarocks install --local luluman-*.rockspec
